### PR TITLE
Support more abstract-leveldown compliant stores

### PR DESCRIPTION
**Pull request by millette**
Like memdown, etc.

### CODE REVIEW

**Comment by millette** [comment]
I'll add relevant changes to the readme (name might not be required, etc.) if this feature is accepted. Oups, gotta standardify first!

**Comment by millette** [comment]
Added a memdown test (and dev dep).

**Comment by mcollina** [comment]
Good work!

**Comment by millette** [comment]
@mcollina I've updated the readme.

**Pull request merged**
